version: '3.9'

services:
  db:
    image: postgres:16
    env_file:
      - ./pg.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"


  web:
    build: .
    volumes:
      - ./src:/src
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
